name: Build and Push Plugin Image

on:
  push:
    branches:
      - main # Or your default branch
  pull_request: # Also build on PRs to check compilation

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Define Image Name
        id: define_image_name
        run: echo "IMAGE_NAME=ghcr.io/${{ github.repository }}/vcluster-nodeport-plugin" >> $GITHUB_ENV

      - name: Build
        run: |
          IMAGE_TAG=${{ github.sha }} make build
          IMAGE_TAG=latest make build

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request' # Don't push on PRs
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3



      - name: push
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: |
          IMAGE_TAG=${{ github.sha }} make push
          IMAGE_TAG=latest make push