name: Build and Push Plugin Image

on:
  push:
    branches:
      - main # Or your default branch
  pull_request: # Also build on PRs to check compilation

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # Specify your Go version

      - name: Build Go binary using Makefile
        run: make build

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request' # Don't push on PRs
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx # Needed for docker build, even if make calls it
        uses: docker/setup-buildx-action@v3

      - name: Define Image Base Name
        id: define_image_base_name
        # github.repository is in the format owner/repository-name
        run: echo "IMAGE_BASE_NAME=ghcr.io/${{ github.repository }}/vcluster-nodeport-patcher" >> $GITHUB_ENV

      - name: Build and Push Docker Image (sha tag) using Makefile
        if: github.event_name != 'pull_request'
        env:
          IMAGE_NAME: ${{ env.IMAGE_BASE_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          make docker-build
          make docker-push

      - name: Build and Push Docker Image (latest tag) using Makefile
        # Only build and push 'latest' tag if on the main branch
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        env:
          IMAGE_NAME: ${{ env.IMAGE_BASE_NAME }}
          IMAGE_TAG: latest
        run: |
          make docker-build
          make docker-push
